version: "2"

services:
  hadoop-graphite-reporter:
    image: wankunde/hadoop-graphite-reporter:latest
    restart: always
    container_name: hadoop-graphite-reporter
    volumes:
      - ./cluster.json:/etc/cluster.json
    network_mode: host