version: "2"

services:
  hadoop-graphite-reporter:
    image: wankunde/hadoop-graphite-reporter:latest
    restart: always
    container_name: hadoop-graphite-reporter
    volumes:
      - ./cluster.json:/etc/cluster.json
    environment:
      GRAPHITE_HOST: localhost
      GRAPHITE_PORT: 2003
      GRAPHITE_PREFIX: hadoop
    network_mode: host